%%Copyright (C) 2024, 2025 John Behan
%%This file is part of Thrive 2050's Android Power Usage app
%%
%%Thrive 2050's Android Power Usage app is free software: you can redistribute it and/or modify
%%it under the terms of the GNU General Public License as published by
%%the Free Software Foundation, either version 3 of the License, or
%%(at your option) any later version.
%%
%%Thrive 2050's Android Power Usage app is distributed in the hope that it will be useful,
%%but WITHOUT ANY WARRANTY; without even the implied warranty of
%%MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%%GNU General Public License for more details.
%%
%%You should have received a copy of the GNU General Public License

sequenceDiagram
    User->>App: Input the URL
    User->>App: Press start button
    App-->>Server: Request video
    loop continuous
        Server-->>App: Stream video
        App-->>App: Record stats

    end
    User->>App: Press stop button
    App-->>Server: Send stats
